// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maqhqiyvyswnwvafgjhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hcWhxaXl2eXN3bnd2YWZnamhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTgwMjUsImV4cCI6MjA3NDM5NDAyNX0.VsFNqWPR1n6e_RO74MP09ihZJQ-4awzYQztyT6c-B88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});